ESX = exports['es_extended']:getSharedObject()

ESX.RegisterUsableItem('box-ammo-22', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-22', 1)
    xPlayer.addInventoryItem('ammo-22', 60)
end)

ESX.RegisterUsableItem('box-ammo-38', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-38', 1)
    xPlayer.addInventoryItem('ammo-38', 60)
end)

ESX.RegisterUsableItem('box-ammo-44', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-44', 1)
    xPlayer.addInventoryItem('ammo-44', 60)
end)

ESX.RegisterUsableItem('box-ammo-9', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-9', 1)
    xPlayer.addInventoryItem('ammo-9', 250)
end)

ESX.RegisterUsableItem('box-ammo-45', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-45', 1)
    xPlayer.addInventoryItem('ammo-45', 60)
end)

ESX.RegisterUsableItem('box-ammo-50', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-50', 1)
    xPlayer.addInventoryItem('ammo-50', 60)
end)

ESX.RegisterUsableItem('box-ammo-shotgun', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-shotgun', 1)
    xPlayer.addInventoryItem('ammo-shotgun', 60)
end)

ESX.RegisterUsableItem('box-ammo-rifle', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-rifle', 1)
    xPlayer.addInventoryItem('ammo-rifle', 250)
end)

ESX.RegisterUsableItem('box-ammo-rifle2', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-rifle2', 1)
    xPlayer.addInventoryItem('ammo-rifle2', 250)
end)

ESX.RegisterUsableItem('box-ammo-sniper', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-sniper', 1)
    xPlayer.addInventoryItem('ammo-sniper', 12)
end)

ESX.RegisterUsableItem('box-ammo-musket', function(playerId)
    local xPlayer = ESX.GetPlayerFromId(playerId)
    xPlayer.removeInventoryItem('box-ammo-musket', 1)
    xPlayer.addInventoryItem('ammo-musket', 8)
end)